name: Run React Application deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository code
        # This action checks-out your repository under $GITHUB_WORKSPACE, 
        # so your workflow can access it.
        uses: actions/checkout@v4
      - name: Install dependecies
        # Install from package-lock.json
        run: npm install
      - name: React Application Test
        run: npm run test
      - name: React Application Lint
        run: npm run lint
      - name: React Application Build
        run: npm run build
      